all_results = [
    {
        "_id": {"$oid": "66544712a4efc40df8ac4e08"},
        "author_id": "tbd",
        "title": "Cap gros",
        "dateCreated": "tbd",
        "description": "Zone escarpée, la mise à l'eau peut-être difficile.dans la baie à la droite du cap il y a possibilité de s'abriter du courant et de trouver des profondeurs inférieures à 10m de fond avec de beaux poissons tout de même.Au bout du cap se situe un plateau à environ 8m de fond suivit du fameux tombant pouvant aller jusqu'à 30m de profondeur, parfait pour un freefall ou simplement pour rester sur le plateau et observer le passage de dorades, sars, mérous et pour les chanceux Dentis et Barracuda. De magnifiques Gorgones ornent le tombant.",
        "characteristics": {
            "suitableFor": "all",
            "fishy": True,
            "reef": True,
            "shipwreck": False,
            "wall": False,
        },
        "image": [],
        "isPublished": True,
        "updateTs": "tbd",
        "lastUpdated": "13/10/2020",
        "latitude": "43.551923",
        "longitude": "7.144933",
        "level": "hard",
        "parking": "Se garer sur l'Avenue André Sella ou au parking de la plage Keller.",
        "address": {
            "city": "Antibes",
            "street": "Avenue André Sella",
            "postalCode": "06600",
            "country": "France",
        },
        "totalRating": 0,
    },
    {
        "_id": {"$oid": "665488505610228a40562419"},
        "author_id": "tbd",
        "title": "Spot 1",
        "dateCreated": "tbd",
        "description": "lorem Ipsum. la droite du cap il y a possibilité de s'abriter du courant et de trouver des profondeurs inférieures à 10m de fond avec de beaux poissons tout de même.Au bout du cap se situe un plateau à environ 8m de fond suivit du fameux tombant pouvant aller jusqu'à 30m de profondeur, parfait pour un freefall ou simplement pour rester sur le plateau et observer le passage de dorades, sars, mérous et pour les chanceux Dentis et Barracuda. De magnifiques Gorgones ornent le tombant.",
        "characteristics": {
            "suitableFor": "all",
            "fishy": True,
            "reef": True,
            "shipwreck": False,
            "wall": False,
        },
        "image": [],
        "isPublished": True,
        "updateTs": "tbd",
        "lastUpdated": "13/10/2020",
        "latitude": "42.591923",
        "longitude": "6.944933",
        "level": "easy",
        "parking": "Se garer sur l'Avenue André Sella ou au parking de la plage Keller.",
        "address": {
            "city": "Marseille",
            "street": "Avenue André Sella",
            "postalCode": "06600",
            "country": "France",
        },
        "totalRating": 0,
    },
    {
        "_id": {"$oid": "66548876b3ce86fff0d8d066"},
        "author_id": "tbd",
        "title": "Spot 3",
        "dateCreated": "tbd",
        "description": "lorem Ipsum. la droite du cap il y a possibilité de s'abriter du courant et de trouver des profondeurs inférieures à 10m de fond avec de beaux poissons tout de même.Au bout du cap se situe un plateau à environ 8m de fond suivit du fameux tombant pouvant aller jusqu'à 30m de profondeur, parfait pour un freefall ou simplement pour rester sur le plateau et observer le passage de dorades, sars, mérous et pour les chanceux Dentis et Barracuda. De magnifiques Gorgones ornent le tombant.",
        "characteristics": {
            "suitableFor": "all",
            "fishy": False,
            "reef": True,
            "shipwreck": False,
            "wall": True,
        },
        "image": [],
        "isPublished": True,
        "updateTs": "tbd",
        "lastUpdated": "13/10/2020",
        "latitude": "42.111923",
        "longitude": "6.144933",
        "level": "medium",
        "parking": "Se garer sur l'Avenue André Sella ou au parking de la plage Keller.",
        "address": {
            "city": "Marseille",
            "street": "Avenue André Sella",
            "postalCode": "06600",
            "country": "France",
        },
        "totalRating": 0,
    },
    {
        "_id": {"$oid": "6654888f4b9811626fc5912a"},
        "author_id": "tbd",
        "title": "Spot 4",
        "dateCreated": "tbd",
        "description": "lorem Ipsum. la droite du cap il y a possibilité de s'abriter du courant et de trouver des profondeurs inférieures à 10m de fond avec de beaux poissons tout de même.Au bout du cap se situe un plateau à environ 8m de fond suivit du fameux tombant pouvant aller jusqu'à 30m de profondeur, parfait pour un freefall ou simplement pour rester sur le plateau et observer le passage de dorades, sars, mérous et pour les chanceux Dentis et Barracuda. De magnifiques Gorgones ornent le tombant.",
        "characteristics": {
            "suitableFor": "all",
            "fishy": False,
            "reef": False,
            "shipwreck": False,
            "wall": True,
        },
        "image": [],
        "isPublished": False,
        "updateTs": "tbd",
        "lastUpdated": "13/11/2020",
        "latitude": "41.141923",
        "longitude": "7.944933",
        "level": "hard",
        "parking": "Se garer sur l'Avenue André Sella ou au parking de la plage Keller.",
        "address": {
            "city": "Marseille",
            "street": "Avenue André Sella",
            "postalCode": "06600",
            "country": "France",
        },
        "totalRating": 0,
    },
    {
        "_id": {"$oid": "665488b2f81a527f8f414a3c"},
        "author_id": "tbd",
        "title": "Spot 5",
        "dateCreated": "tbd",
        "description": "lorem Ipsum. la droite du cap il y a possibilité de s'abriter du courant et de trouver des profondeurs inférieures à 10m de fond avec de beaux poissons tout de même.Au bout du cap se situe un plateau à environ 8m de fond suivit du fameux tombant pouvant aller jusqu'à 30m de profondeur, parfait pour un freefall ou simplement pour rester sur le plateau et observer le passage de dorades, sars, mérous et pour les chanceux Dentis et Barracuda. De magnifiques Gorgones ornent le tombant.",
        "characteristics": {
            "suitableFor": "all",
            "fishy": False,
            "reef": True,
            "shipwreck": False,
            "wall": True,
        },
        "image": [],
        "isPublished": False,
        "updateTs": "tbd",
        "lastUpdated": "11/10/2020",
        "latitude": "41.621923",
        "longitude": "7.114933",
        "level": "hard",
        "parking": "Se garer sur l'Avenue André Sella ou au parking de la plage Keller.",
        "address": {
            "city": "Marseille",
            "street": "Avenue André Sella",
            "postalCode": "06600",
            "country": "France",
        },
        "totalRating": 0,
    },
]
